// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectonew.Data;

#nullable disable

namespace proyectonew.Migrations
{
    [DbContext(typeof(SivDbContext))]
    [Migration("20260711015304_AgregarPuertaYModuloCambios")]
    partial class AgregarPuertaYModuloCambios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyectonew.Models.Aerolinea", b =>
                {
                    b.Property<int>("AerolineaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AerolineaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AerolineaId");

                    b.ToTable("Aerolineas");
                });

            modelBuilder.Entity("proyectonew.Models.Aeropuerto", b =>
                {
                    b.Property<int>("AeropuertoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AeropuertoId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AeropuertoId");

                    b.ToTable("Aeropuertos");
                });

            modelBuilder.Entity("proyectonew.Models.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditoriaId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("proyectonew.Models.CambioOperativo", b =>
                {
                    b.Property<int>("CambioOperativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CambioOperativoId"));

                    b.Property<string>("Causa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("CambioOperativoId");

                    b.HasIndex("VueloId");

                    b.ToTable("CambiosOperativos");
                });

            modelBuilder.Entity("proyectonew.Models.EstadoVuelo", b =>
                {
                    b.Property<int>("EstadoVueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoVueloId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoVueloId");

                    b.ToTable("EstadosVuelo");
                });

            modelBuilder.Entity("proyectonew.Models.HistorialEstadoVuelo", b =>
                {
                    b.Property<int>("HistorialEstadoVueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialEstadoVueloId"));

                    b.Property<int>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("HistorialEstadoVueloId");

                    b.HasIndex("VueloId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("proyectonew.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId");

                    b.HasIndex("VueloId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("proyectonew.Models.Seguimiento", b =>
                {
                    b.Property<int>("SeguimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguimientoId"));

                    b.Property<DateTime>("FechaSeguimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("SeguimientoId");

                    b.HasIndex("VueloId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("proyectonew.Models.Vuelo", b =>
                {
                    b.Property<int>("VueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VueloId"));

                    b.Property<int>("AerolineaId")
                        .HasColumnType("int");

                    b.Property<int>("AeropuertoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("AeropuertoOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoVueloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioProgramado")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Puerta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("VueloId");

                    b.HasIndex("AerolineaId");

                    b.HasIndex("AeropuertoDestinoId");

                    b.HasIndex("AeropuertoOrigenId");

                    b.HasIndex("EstadoVueloId");

                    b.ToTable("Vuelos", (string)null);
                });

            modelBuilder.Entity("proyectonew.Models.CambioOperativo", b =>
                {
                    b.HasOne("proyectonew.Models.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("proyectonew.Models.HistorialEstadoVuelo", b =>
                {
                    b.HasOne("proyectonew.Models.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("proyectonew.Models.Notificacion", b =>
                {
                    b.HasOne("proyectonew.Models.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("proyectonew.Models.Seguimiento", b =>
                {
                    b.HasOne("proyectonew.Models.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("proyectonew.Models.Vuelo", b =>
                {
                    b.HasOne("proyectonew.Models.Aerolinea", "Aerolinea")
                        .WithMany()
                        .HasForeignKey("AerolineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectonew.Models.Aeropuerto", "AeropuertoDestino")
                        .WithMany()
                        .HasForeignKey("AeropuertoDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectonew.Models.Aeropuerto", "AeropuertoOrigen")
                        .WithMany()
                        .HasForeignKey("AeropuertoOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectonew.Models.EstadoVuelo", "EstadoVuelo")
                        .WithMany()
                        .HasForeignKey("EstadoVueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aerolinea");

                    b.Navigation("AeropuertoDestino");

                    b.Navigation("AeropuertoOrigen");

                    b.Navigation("EstadoVuelo");
                });
#pragma warning restore 612, 618
        }
    }
}
